### ISSUE TITLE
Mehrsprachigkeit

### ISSUE THREAD

**Issue by axelvondreden** [axelvondreden/dms#1]

**Comment by HeyDennis** [comment]
Habe noch einen Dialog entdeckt.
![grafik](https://user-images.githubusercontent.com/47058862/78746656-bb593700-7967-11ea-9374-33220b7a0e7f.png)


Ist eine englische Variante schon vorhanden ?
Da beim umsetzen nichts geschieht

![grafik](https://user-images.githubusercontent.com/47058862/78746675-cb711680-7967-11ea-86ce-601b4f9bf731.png)

![grafik](https://user-images.githubusercontent.com/47058862/78746726-e5aaf480-7967-11ea-93a7-9901878bccff.png)
