### ISSUE TITLE
Check-Up View

### ISSUE THREAD

**Issue by HeyDennis** [axelvondreden/dms#10]
Create a new view for check-up new doc's.
All doc's need a lable or flag like checked/unchecked

- Split-screen with PDF and TEXT
- Rotate
- Cut
- Check existing OCR with intern OCR and view differents
- Find and set automatically labels
- Click on words for create new labels

**Comment by axelvondreden** [comment]
Ich mache das jetzt auch mal zu, weil einges schon implementiert wurde. Für den Rest dann Einzeltickets nach 0.2

**Comment by HeyDennis** [comment]
ok
