### ISSUE TITLE
Dokument hochladen -> verschieben ?

### ISSUE THREAD

**Issue by HeyDennis** [axelvondreden/dms#121]
Der Upload könnte mit in die Ansicht Import oder was meinst du ?

![grafik](https://user-images.githubusercontent.com/47058862/80892455-86bc6f00-8cca-11ea-977e-db52af229894.png)

**Comment by axelvondreden** [comment]
Ja, gute Idee

**Comment by HeyDennis** [comment]
Beim Hochladen sieht man nun kein Fortschritt mehr....
Ist das Absicht ?

**Comment by HeyDennis** [comment]
Nach Upload wäre ein automatisches Ansicht aktualisieren cool

**Comment by axelvondreden** [comment]
Den Fortschritt siehst du schon, wenn du auf aktualisieren drückst. Kann bis zu 10s dauern, bis er anfängt zu speichern

**Comment by HeyDennis** [comment]
Nein mir geht es wirklich um das Upload Pop-Up.
Dort gab es früher pro Datei Fortschrittsbalken zum Upload.

**Comment by axelvondreden** [comment]
Weiß nicht ganz was du meinst. Bei mir war der Dialog nie länger als 2 Sekunden auf, solange du dms auf localhost hast. Bei 50+ files hat es zwar länger gedauert, aber ohne wirklichen Fortschritt, eher ruckelig.

**Comment by HeyDennis** [comment]
stimmt... seltsam warum es sich bei 2-3 Dokumenten bei mir ca. 10 Sekunden Zeit lässt....
