### ISSUE TITLE
Internal OCR

### ISSUE THREAD

**Issue by axelvondreden** [axelvondreden/dms#22]

**Comment by HeyDennis** [comment]
Sollte die Sprache nicht alle möglichen beinhalten anstatt nur eine zu brücksichtigen ?
Wenn man nun deutsche und Englische Dokumente hat ?!

**Comment by HeyDennis** [comment]
Beim Upload von Dokumenten sollte man eine Option haben ob diese durch den internen OCR überarbeitet werden sollten oder nicht.
Oder meinst du wir sollten einen Vergleich fahren zwischen Input OCR und Internal OCR ? Und beide im Doc speichern ?

**Comment by HeyDennis** [comment]
Bei ein paar Test hat die interne OCR nicht so gut abgeschnitten : 

![grafik](https://user-images.githubusercontent.com/47058862/76201945-5db0be00-61f4-11ea-8ee8-2017dd7d6fe6.png)
