### ISSUE TITLE
Tag mail als Spezial-Tag

### ISSUE THREAD

**Issue by HeyDennis** [axelvondreden/dms#42]
Ein Spezial-Tag über die Properties definieren welche alle einkommenden Docs aus dem IMAP Konto definiert.

Standard-Attribute dafür wären:
- Empfänger
- Absender
- Datum
- Firma

Das Standard-Attribute (aktuell Review würde ich auch vergeben)

**Comment by axelvondreden** [comment]
Hat sich erstmal erledigt durch die Einführung von Mail-Elementen
