### ISSUE TITLE
Tag's löschen

### ISSUE THREAD

**Issue by HeyDennis** [axelvondreden/dms#70]
Option zum löschen von Tag's hinzufügen.

mögliche Probleme:

- löschen von in Doc's zugeordneten Tag's
  - mögliche Lösung: sperren, Tag's in Doc's entfernen, nichts unternehmen
- löschen von in Regeln zugeordneten Tag's
  - mögliche Lösung: sperren, Tag's in Regeln entfernen, nichts unternehmen
- Attribute-Zuordung bleibt bestehen
  - gibt es dazu eine Verknüpfungstabelle oder besteht hier kein Handlungsbedarf ?

**Comment by HeyDennis** [comment]
Regeln werden nicht beachtet.

**Comment by axelvondreden** [comment]
?

**Comment by axelvondreden** [comment]
> 
> 
> Regeln werden nicht beachtet.

?

gelöschte Tags werden auch in den Regeln entfernt

**Comment by HeyDennis** [comment]
ah okay... ich habe es so verstanden, dass es gesperrt werden soll....
