### ISSUE TITLE
Automatic Tag - contained

### ISSUE THREAD

**Issue by HeyDennis** [axelvondreden/dms#73]
In den Optionen ermöglichen "contained" Tags automatisch zu setzen.
In den Optionen ermöglichen "contained" Sucheinstellungen zu setzen. (*Tag*)
  -> evtl. Suchzeichen in Tag verlagern

**Comment by axelvondreden** [comment]
Kann über Regeln abgebildet werden, deshalb niedrige Prio

**Comment by HeyDennis** [comment]
Ja.,.. schieben wir erstmal...

**Comment by HeyDennis** [comment]
durch die Umgestaltung evtl . erledigt. -> #19
