### ISSUE TITLE
Papierkorb

### ISSUE THREAD

**Issue by HeyDennis** [axelvondreden/dms#77]
Gelöschte Daten in Papierkorb verwahren.

- Docs
- Attributes
- Tags
- Rules
- Mails

**Comment by HeyDennis** [comment]
gerade bei Tag löschen und ausversehen Docs mit anklicken sonst bei einem großem Datenbestand gefährlich

**Comment by HeyDennis** [comment]
Wenn Dokumente über die Kategorie gelöscht werden landen diese nicht im Papierkorb.

**Comment by axelvondreden** [comment]
> Wenn Dokumente über die Kategorie gelöscht werden landen diese nicht im Papierkorb.

Werde die Option erstmal deaktivieren. Dann schauen wir nochmal, nachdem das Konstrukt evtl. umgebaut wurde.

**Comment by HeyDennis** [comment]
Du wirst es besser wissen... ABER das Konstrukt Kategorie bleibt ja...
Aber ja die Funktion die Dokumente zu löschen muss man auch nicht haben, da man dies ja vorher über die Suche löschen kann...
