### ISSUE TITLE
Textfeldgröße

### ISSUE THREAD

**Issue by HeyDennis** [axelvondreden/dms#80]
Die Textfelder wollten wir auch deutlich kleiner machen oder ?
Eigtl. reicht es ja je Wort

Oder fallen dir gerade Nachteile ein ?

`Caused by: org.h2.jdbc.JdbcSQLDataException: Wert zu gross / lang für Feld "MESSAGE VARCHAR(255)": "STRINGDECODE('Created TextBlock(\u2022-tij`L-#`ri:\u20ac''\u00d6`j2*,\u00e4riJ;'':..-;iffi\u00e4d?].`\u00e4`.i\u00c4:*-ffi;#~i\u... (612)"
Value too long for column "MESSAGE VARCHAR(255)": "STRINGDECODE('Created TextBlock(\u2022-tij`L-#`ri:\u20ac''\u00d6`j2*,\u00e4riJ;'':..-;iffi\u00e4d?].`\u00e4`.i\u00c4:*-ffi;#~i\u... (612)"; SQL statement:`

**Comment by axelvondreden** [comment]
Ideal wäre wahrscheinlich, Wörter einzeln zu speichern und zusätzlich gesammelt als "Satz".

Nachteil ist wahrscheinlich Speicherplatz, wenn dann zu jedem Wort die z.B. die Positionsdaten gespeichert werden. Muss man aber ausprobieren
