### ISSUE TITLE
Installation 0.2 / Stillstand bei Start PS

### ISSUE THREAD

**Issue by HeyDennis** [axelvondreden/dms#90]
DMS bleibt stehen bei
`2020-04-07 15:36:12.886  INFO 20436 --- [           main] com.dude.dms.brain.FileManager           : Generiere Ordner f³r Dokumente; docs`

Habe den ganzen DMS Ordner vorher gelöscht und neu heruntergeladen
auch Tasten drücken bringt nichts
auch erneut schließen und starten bringt nichts
nach neu starten bleibt er bei einem Log Eintrag zuvor hängen :
`2020-04-07 15:44:36.101  INFO 2064 --- [           main] com.dude.dms.updater.UpdateChecker       : Neueste Version ist bereits installiert: 0.2`

**Comment by axelvondreden** [comment]
OK das ganze ist wohl ein Missverständnis, weil ich die Logs etwas ausgedünnt habe:
Das sind einfach die letzten Logeinträge...DMS müsste zu diesem Zeitpunkt schon laufen.
Ein paar Zeilen drüber sollte bei dir eigentlich auch folgender Eintrag sein:

`2020-04-07 18:52:31.950  INFO 11008 --- [           main] com.dude.dms.Application                 : Started Application in 19.269 seconds (JVM running for 19.777)`

Werde dann im nächsten Release noch sowas wie "Erfolgreich gestartet" andrucken.
