### ISSUE TITLE
Dokumente importieren - OCR (intern + PDF) - Rechtschreibprüfung

### ISSUE THREAD

**Issue by HeyDennis** [axelvondreden/dms#92]
Die Übersicht wie viele Wörter in der OCR erkannt wurden und in der PDF ist sehr gut.
Um die Qualtiät besser einschätzen zu können oder auch sich Problemstellen besser ansehen zu können wäre ein Rechtschreibprüfung von Vorteil.

Das Ergebnis würde ich beim Import zusätzlich anzeigen.

Ideal wäre ein highlighting in der Textvorschau.

**Comment by HeyDennis** [comment]
Super

Ist das Highlighting jetzt für den Vergleich PDF/OCR oder für die Rechtschreibung ?
Wäre beide möglich ? (unterschliedliche Farben zum Beispiel) ?

**Comment by axelvondreden** [comment]
Highlight ist für die Rechtschreibung.
OCR und PDF wissen aktuell nichts von einander, deshalb ist hier der Vergleich erstmal nicht so einfach.
Wäre ja den eh hier: #104
