### ISSUE TITLE
Textfelder löschen - Überlappung

### ISSUE THREAD

**Issue by HeyDennis** [axelvondreden/dms#96]
![grafik](https://user-images.githubusercontent.com/47058862/78746147-636e0080-7966-11ea-8c5b-2afc157c330c.png)

Wenn sich Textfelder überlappen kommt man mit der Maus nicht an die Symbole, da dann das andere Textfeld aktiviert wird.

Vorschläge wären:
Kontextmenü (Rechtsklick) erstellen
Textfeld durch einfachen Linksklick auswählen - Doppelten Linksklick bearbeiten

**Comment by axelvondreden** [comment]
Der Block im Beispiel würde doch eh gelöscht werden, oder?
Ist das wirklich ein Problem bei richtiger Anwendung?

**Comment by HeyDennis** [comment]
Klar im Beispiel hat er Jech nicht richtig erkannt...
aber wenn er nun das obere richtig erkennt und das untere nicht....

Klar ist keine High Prio aber schon ein Thema

**Comment by HeyDennis** [comment]
Ich meine es ist etwas besser (weiß nicht warum...)
Aber wenn man eine wirkliche Überlappung hat gibt es keine Chance außer löschen...

Aber kann auch erstmal zurückgestellt werden....

**Comment by HeyDennis** [comment]
Das Umstellen auf Akton löschen statt edit lässt es ja nun ermöglichen....
