### ISSUE TITLE
Textfelder in Ansicht - Mehrfachauswahl

### ISSUE THREAD

**Issue by HeyDennis** [axelvondreden/dms#97]
Das erstellen von Textfeldern funktioniert mit Rechts und Links Klick. (sehr schöne Funktion)

In Bereichen von Logos etc können sehr viele unnütze Textfelder entstehen.
Diese wären leichter zu löschen wenn man mehrere Textfelder auswählen kann.(durch aufziehen eines Rechtecks)

Am PC hätte ich gesagt Auswahl erfolgt durch Rechte Taste gedrückt halten.
Dies wäre aber an mobile Geräte nicht umsetzbar.

Fällt dir noch etwa besseres ein ?

Evtl. wie in Acrobat Reader ein Auswahl und Bearbeiten Modus ?

**Comment by axelvondreden** [comment]
Auswahl durch rechte Maustaste ist umgesetzt.
Mobilgeräte sind schon lange vom Tisch mit Tooltips, Dialogen und dem Importprozess

**Comment by HeyDennis** [comment]
du machst auch einfach das was ich sage oder ? :-)
freut micht ja.. aber ... wann wählt man Dinge dann bitte mit der rechten Maus Taste aus...
Es ist immer die linke.. und Rechts ist Kontextmenü...

**Comment by HeyDennis** [comment]
toll !
