### ISSUE TITLE
Bearbeiten Dialog - Attribute befüllen - Anzeigefehler

### ISSUE THREAD

**Issue by HeyDennis** [axelvondreden/dms#98]
Vor Klick 
![grafik](https://user-images.githubusercontent.com/47058862/78746790-1428cf80-7968-11ea-914b-f1d51ccf7e53.png)

Nach Klick:
![grafik](https://user-images.githubusercontent.com/47058862/78746801-1e4ace00-7968-11ea-900b-3a46a85349ac.png)

**Comment by axelvondreden** [comment]
Funktioniert bei mir.
Attribute sind vorhanden, oder?
Verhalten immer so?

**Comment by HeyDennis** [comment]
-_-*
